//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Bill_Mapping : EntityTypeConfiguration<Bill>
    {
        public Bill_Mapping()
        {					
    		this.HasKey(t => new {t.RecordId, t.Memoryid});		
    		this.ToTable("Bills");
    		this.Property(t => t.RecordId).HasColumnName("RecordId").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
    		this.Property(t => t.Memoryid).HasColumnName("Memoryid").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
    		this.Property(t => t.Memorycard).HasColumnName("Memorycard").IsUnicode(false).HasMaxLength(50);
    		this.Property(t => t.Customerid).HasColumnName("Customerid");
    		this.Property(t => t.Customername).HasColumnName("Customername").IsUnicode(false).HasMaxLength(50);
    		this.Property(t => t.Shortname).HasColumnName("Shortname").IsRequired().IsUnicode(false).HasMaxLength(20);
    		this.Property(t => t.Ispay).HasColumnName("Ispay");
    		this.Property(t => t.Scustomerid).HasColumnName("Scustomerid").IsUnicode(false).HasMaxLength(20);
    		this.Property(t => t.Scustomername).HasColumnName("Scustomername").IsUnicode(false).HasMaxLength(50);
    		this.Property(t => t.ProId).HasColumnName("ProId");
    		this.Property(t => t.Proname).HasColumnName("Proname").IsUnicode(false).HasMaxLength(100);
    		this.Property(t => t.Startweight).HasColumnName("Startweight");
    		this.Property(t => t.Endweight).HasColumnName("Endweight");
    		this.Property(t => t.Inweight).HasColumnName("Inweight");
    		this.Property(t => t.Outweight).HasColumnName("Outweight");
    		this.Property(t => t.Stockindate).HasColumnName("Stockindate");
    		this.Property(t => t.Startdate).HasColumnName("Startdate");
    		this.Property(t => t.Endate).HasColumnName("Endate");
    		this.Property(t => t.Enddays).HasColumnName("Enddays");
    		this.Property(t => t.Rate).HasColumnName("Rate");
    		this.Property(t => t.Status).HasColumnName("Status").IsUnicode(false).HasMaxLength(20);
    		this.Property(t => t.Createuser).HasColumnName("Createuser").IsUnicode(false).HasMaxLength(50);
    		this.Property(t => t.Createtime).HasColumnName("Createtime");
    		this.HasRequired(t => t.BillRecord).WithMany(t => t.Bills).HasForeignKey(d => d.RecordId);
    		this.HasOptional(t => t.Customer).WithMany(t => t.Bills).HasForeignKey(d => d.Customerid);
    	}
    }
}
