//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class BillDetail_Mapping : EntityTypeConfiguration<BillDetail>
    {
        public BillDetail_Mapping()
        {					
    		this.HasKey(t => t.Bid);		
    		this.ToTable("BillDetails");
    		this.Property(t => t.Bid).HasColumnName("Bid");
    		this.Property(t => t.Recordid).HasColumnName("Recordid");
    		this.Property(t => t.Memoryid).HasColumnName("Memoryid");
    		this.Property(t => t.Memorycard).HasColumnName("Memorycard").IsRequired().HasMaxLength(50);
    		this.Property(t => t.CustomerId).HasColumnName("CustomerId");
    		this.Property(t => t.Itemtime).HasColumnName("Itemtime");
    		this.Property(t => t.Subject).HasColumnName("Subject").HasMaxLength(50);
    		this.Property(t => t.Inweight).HasColumnName("Inweight");
    		this.Property(t => t.Outweight).HasColumnName("Outweight");
    		this.Property(t => t.Sweight).HasColumnName("Sweight");
    		this.Property(t => t.Rate).HasColumnName("Rate");
    		this.Property(t => t.Days).HasColumnName("Days");
    		this.Property(t => t.Computation).HasColumnName("Computation");
    		this.Property(t => t.Storefee).HasColumnName("Storefee");
    		this.Property(t => t.Status).HasColumnName("Status").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Createuser).HasColumnName("Createuser").HasMaxLength(50);
    		this.Property(t => t.Createtime).HasColumnName("Createtime");
    		this.HasRequired(t => t.BillRecord).WithMany(t => t.BillDetails).HasForeignKey(d => d.Recordid);
    		this.HasRequired(t => t.Customer).WithMany(t => t.BillDetails).HasForeignKey(d => d.CustomerId);
    		this.HasRequired(t => t.Memorycard1).WithMany(t => t.BillDetails).HasForeignKey(d => d.Memoryid);
    	}
    }
}
