//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Button_Mapping : EntityTypeConfiguration<Button>
    {
        public Button_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("Buttons");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.About).HasColumnName("About").HasMaxLength(30);
    		this.Property(t => t.SysController).HasColumnName("SysController").IsRequired().HasMaxLength(30);
    		this.Property(t => t.SysAction).HasColumnName("SysAction").IsRequired().HasMaxLength(30);
    		this.Property(t => t.Sort).HasColumnName("Sort");
    		this.Property(t => t.MenuId).HasColumnName("MenuId");
    		this.Property(t => t.Icon).HasColumnName("Icon").IsRequired().HasMaxLength(100);
    		this.Property(t => t.Status).HasColumnName("Status").IsRequired().HasMaxLength(2);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").IsRequired().HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.HasMany(t => t.Roles).WithMany(t => t.Buttons)
    			.Map(m => 
    			{
    				m.ToTable("RoleButton");
    				m.MapLeftKey("ButtonId");
    				m.MapRightKey("RoleId");
    			});
    	}
    }
}
