//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Charge_Mapping : EntityTypeConfiguration<Charge>
    {
        public Charge_Mapping()
        {					
    		this.HasKey(t => t.ChargeId);		
    		this.ToTable("Charge");
    		this.Property(t => t.ChargeId).HasColumnName("ChargeId");
    		this.Property(t => t.Type).HasColumnName("Type").HasMaxLength(20);
    		this.Property(t => t.Price).HasColumnName("Price");
    		this.Property(t => t.Date).HasColumnName("Date");
    		this.Property(t => t.Amount).HasColumnName("Amount");
    	}
    }
}
