//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class ContractRate_Mapping : EntityTypeConfiguration<ContractRate>
    {
        public ContractRate_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("ContractRates");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.Conid).HasColumnName("Conid");
    		this.Property(t => t.Manualno).HasColumnName("Manualno").HasMaxLength(20);
    		this.Property(t => t.Proid).HasColumnName("Proid");
    		this.Property(t => t.Rjdj).HasColumnName("Rjdj");
    		this.Property(t => t.Rjrgsj).HasColumnName("Rjrgsj");
    		this.Property(t => t.Rjtlzxlf).HasColumnName("Rjtlzxlf");
    		this.Property(t => t.Rjsz).HasColumnName("Rjsz");
    		this.Property(t => t.Rtrkysf).HasColumnName("Rtrkysf");
    		this.Property(t => t.Rtrgsj).HasColumnName("Rtrgsj");
    		this.Property(t => t.Rttlgyf).HasColumnName("Rttlgyf");
    		this.Property(t => t.Rtdbf).HasColumnName("Rtdbf");
    		this.Property(t => t.Rgrkjyf).HasColumnName("Rgrkjyf");
    		this.Property(t => t.Rgrgsj).HasColumnName("Rgrgsj");
    		this.Property(t => t.Rgdbf).HasColumnName("Rgdbf");
    		this.Property(t => t.Rjzxrkysf).HasColumnName("Rjzxrkysf");
    		this.Property(t => t.Rjzxrgsj).HasColumnName("Rjzxrgsj");
    		this.Property(t => t.Rjzxtxf).HasColumnName("Rjzxtxf");
    		this.Property(t => t.Rjzxdbf).HasColumnName("Rjzxdbf");
    		this.Property(t => t.Rjzxdbstart).HasColumnName("Rjzxdbstart");
    		this.Property(t => t.Rjzxdbend).HasColumnName("Rjzxdbend");
    		this.Property(t => t.Cckf).HasColumnName("Cckf");
    		this.Property(t => t.Cchc).HasColumnName("Cchc");
    		this.Property(t => t.Ccrkmfqstart).HasColumnName("Ccrkmfqstart");
    		this.Property(t => t.Ccrkmfqend).HasColumnName("Ccrkmfqend");
    		this.Property(t => t.Ccrkmfqday).HasColumnName("Ccrkmfqday");
    		this.Property(t => t.Ccykf).HasColumnName("Ccykf");
    		this.Property(t => t.Ccyhc).HasColumnName("Ccyhc");
    		this.Property(t => t.Ckqc).HasColumnName("Ckqc");
    		this.Property(t => t.Ckjjr).HasColumnName("Ckjjr");
    		this.Property(t => t.Ghf).HasColumnName("Ghf");
    		this.Property(t => t.Fjf).HasColumnName("Fjf");
    		this.Property(t => t.Sjts).HasColumnName("Sjts");
    		this.Property(t => t.Sjtp).HasColumnName("Sjtp");
    		this.Property(t => t.Sjsg).HasColumnName("Sjsg");
    		this.Property(t => t.Status).HasColumnName("Status").HasMaxLength(20);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.HasRequired(t => t.Contract).WithMany(t => t.ContractRates).HasForeignKey(d => d.Conid);
    		this.HasRequired(t => t.Product).WithMany(t => t.ContractRates).HasForeignKey(d => d.Proid);
    	}
    }
}
