//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Contract_Mapping : EntityTypeConfiguration<Contract>
    {
        public Contract_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("Contracts");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.Manualno).HasColumnName("Manualno").HasMaxLength(20);
    		this.Property(t => t.Customerid).HasColumnName("Customerid");
    		this.Property(t => t.Mncode).HasColumnName("Mncode").HasMaxLength(20);
    		this.Property(t => t.Israilway).HasColumnName("Israilway");
    		this.Property(t => t.Ishighway).HasColumnName("Ishighway");
    		this.Property(t => t.Iscontainer).HasColumnName("Iscontainer");
    		this.Property(t => t.Isexpire).HasColumnName("Isexpire");
    		this.Property(t => t.Settday).HasColumnName("Settday");
    		this.Property(t => t.Delaycost).HasColumnName("Delaycost");
    		this.Property(t => t.Startime).HasColumnName("Startime");
    		this.Property(t => t.Endtime).HasColumnName("Endtime");
    		this.Property(t => t.Demoid).HasColumnName("Demoid").HasMaxLength(20);
    		this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(255);
    		this.Property(t => t.Status).HasColumnName("Status").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").IsRequired().HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.HasOptional(t => t.Customer).WithMany(t => t.Contracts).HasForeignKey(d => d.Customerid);
    	}
    }
}
