//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Customer_Mapping : EntityTypeConfiguration<Customer>
    {
        public Customer_Mapping()
        {					
    		this.HasKey(t => t.CustomerId);		
    		this.ToTable("Customers");
    		this.Property(t => t.CustomerId).HasColumnName("CustomerId");
    		this.Property(t => t.CustomerName).HasColumnName("CustomerName").IsRequired().HasMaxLength(50);
    		this.Property(t => t.ShortName).HasColumnName("ShortName").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(50);
    		this.Property(t => t.MnCode).HasColumnName("MnCode").HasMaxLength(50);
    		this.Property(t => t.Phones).HasColumnName("Phones").HasMaxLength(25);
    		this.Property(t => t.Contract).HasColumnName("Contract").HasMaxLength(20);
    		this.Property(t => t.Status).HasColumnName("Status").IsRequired().HasMaxLength(2);
    		this.Property(t => t.PostCode).HasColumnName("PostCode").HasMaxLength(10);
    		this.Property(t => t.Remarks).HasColumnName("Remarks").HasMaxLength(400);
    		this.Property(t => t.Manualno).HasColumnName("Manualno").HasMaxLength(20);
    		this.Property(t => t.Fexs).HasColumnName("Fexs").HasMaxLength(20);
    		this.Property(t => t.Banks).HasColumnName("Banks").HasMaxLength(500);
    		this.Property(t => t.Account).HasColumnName("Account").HasMaxLength(20);
    		this.Property(t => t.Mobiles).HasColumnName("Mobiles").HasMaxLength(50);
    		this.Property(t => t.Emails).HasColumnName("Emails").HasMaxLength(255);
    		this.Property(t => t.Idcard).HasColumnName("Idcard").HasMaxLength(20);
    		this.Property(t => t.Trade).HasColumnName("Trade");
    		this.Property(t => t.Sign).HasColumnName("Sign");
    		this.Property(t => t.Isbatch).HasColumnName("Isbatch");
    		this.Property(t => t.LastExport).HasColumnName("LastExport");
    		this.Property(t => t.Ispay).HasColumnName("Ispay");
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").IsRequired().HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.HasMany(t => t.Groups).WithMany(t => t.Customers)
    			.Map(m => 
    			{
    				m.ToTable("CustomerGroup");
    				m.MapLeftKey("CustomerId");
    				m.MapRightKey("Groupid");
    			});
    	}
    }
}
