//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Group_Mapping : EntityTypeConfiguration<Group>
    {
        public Group_Mapping()
        {					
    		this.HasKey(t => t.Groupid);		
    		this.ToTable("Groups");
    		this.Property(t => t.Groupid).HasColumnName("Groupid");
    		this.Property(t => t.Groupname).HasColumnName("Groupname").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Status).HasColumnName("Status").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").IsRequired().HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    	}
    }
}
