//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Job_Mapping : EntityTypeConfiguration<Job>
    {
        public Job_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("Jobs");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(500);
    		this.Property(t => t.Status).HasColumnName("Status").IsRequired().IsFixedLength().HasMaxLength(1);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").IsRequired().HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    	}
    }
}
