//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Memorycard_Mapping : EntityTypeConfiguration<Memorycard>
    {
        public Memorycard_Mapping()
        {					
    		this.HasKey(t => t.Memoryid);		
    		this.ToTable("Memorycards");
    		this.Property(t => t.Memoryid).HasColumnName("Memoryid");
    		this.Property(t => t.MemorycardName).HasColumnName("Memorycard").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Stockinid).HasColumnName("Stockinid").HasMaxLength(20);
    		this.Property(t => t.Smanualno).HasColumnName("Smanualno").HasMaxLength(20);
    		this.Property(t => t.Recargoid).HasColumnName("Recargoid").HasMaxLength(20);
    		this.Property(t => t.Manualno).HasColumnName("Manualno").HasMaxLength(20);
    		this.Property(t => t.Customerid).HasColumnName("Customerid");
    		this.Property(t => t.Customername).HasColumnName("Customername").HasMaxLength(50);
    		this.Property(t => t.Conid).HasColumnName("Conid").HasMaxLength(20);
    		this.Property(t => t.Mncode).HasColumnName("Mncode").HasMaxLength(20);
    		this.Property(t => t.Arrivalwayid).HasColumnName("Arrivalwayid").HasMaxLength(20);
    		this.Property(t => t.Arrivalwayname).HasColumnName("Arrivalwayname").HasMaxLength(50);
    		this.Property(t => t.Carno).HasColumnName("Carno").HasMaxLength(50);
    		this.Property(t => t.Acceptanceid).HasColumnName("Acceptanceid").HasMaxLength(20);
    		this.Property(t => t.Acceptance).HasColumnName("Acceptance").HasMaxLength(50);
    		this.Property(t => t.Sid).HasColumnName("Sid").HasMaxLength(20);
    		this.Property(t => t.Contactor).HasColumnName("Contactor").HasMaxLength(20);
    		this.Property(t => t.Proid).HasColumnName("Proid").HasMaxLength(20);
    		this.Property(t => t.Proname).HasColumnName("Proname").HasMaxLength(100);
    		this.Property(t => t.Brandname).HasColumnName("Brandname").HasMaxLength(100);
    		this.Property(t => t.Moname).HasColumnName("Moname").HasMaxLength(100);
    		this.Property(t => t.Maname).HasColumnName("Maname").HasMaxLength(100);
    		this.Property(t => t.Baname).HasColumnName("Baname").HasMaxLength(100);
    		this.Property(t => t.Hottoys).HasColumnName("Hottoys");
    		this.Property(t => t.Qunit).HasColumnName("Qunit").HasMaxLength(100);
    		this.Property(t => t.Wunit).HasColumnName("Wunit").HasMaxLength(100);
    		this.Property(t => t.Scurinrpieces).HasColumnName("Scurinrpieces");
    		this.Property(t => t.ScurinWeight).HasColumnName("ScurinWeight");
    		this.Property(t => t.Scuroutrpieces).HasColumnName("Scuroutrpieces");
    		this.Property(t => t.ScuroutWeight).HasColumnName("ScuroutWeight");
    		this.Property(t => t.Srpieces).HasColumnName("Srpieces");
    		this.Property(t => t.Sweight).HasColumnName("Sweight");
    		this.Property(t => t.Status).HasColumnName("Status").HasMaxLength(20);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.Property(t => t.Supplyunit).HasColumnName("Supplyunit").HasMaxLength(50);
    		this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(255);
    		this.Property(t => t.Isallstockin).HasColumnName("Isallstockin");
    		this.Property(t => t.Scustomerid).HasColumnName("Scustomerid").HasMaxLength(20);
    		this.Property(t => t.Scustomername).HasColumnName("Scustomername").HasMaxLength(50);
    		this.Property(t => t.Stockindate).HasColumnName("Stockindate");
    		this.Property(t => t.Sourceorder).HasColumnName("Sourceorder").HasMaxLength(20);
    		this.HasOptional(t => t.Customer).WithMany(t => t.Memorycards).HasForeignKey(d => d.Customerid);
    	}
    }
}
