//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Menu_Mapping : EntityTypeConfiguration<Menu>
    {
        public Menu_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("Menus");
    		this.Property(t => t.Id).HasColumnName("Id");
    		this.Property(t => t.DisplayName).HasColumnName("DisplayName").IsRequired().HasMaxLength(30);
    		this.Property(t => t.DisplayIcon).HasColumnName("DisplayIcon").IsRequired().HasMaxLength(100);
    		this.Property(t => t.MenuNo).HasColumnName("MenuNo").HasMaxLength(50);
    		this.Property(t => t.ParentId).HasColumnName("ParentId");
    		this.Property(t => t.Sort).HasColumnName("Sort");
    		this.Property(t => t.Status).HasColumnName("Status").HasMaxLength(2);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").IsRequired().HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.HasOptional(t => t.Menu1).WithMany(t => t.ChildMenus).HasForeignKey(d => d.ParentId);
    		this.HasMany(t => t.Roles).WithMany(t => t.Menus)
    			.Map(m => 
    			{
    				m.ToTable("RoleMenu");
    				m.MapLeftKey("MenuId");
    				m.MapRightKey("RoleId");
    			});
    	}
    }
}
