//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Rack_Mapping : EntityTypeConfiguration<Rack>
    {
        public Rack_Mapping()
        {					
    		this.HasKey(t => t.Rackid);		
    		this.ToTable("Racks");
    		this.Property(t => t.Rackid).HasColumnName("Rackid").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Rackname).HasColumnName("Rackname").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Racktype).HasColumnName("Racktype").HasMaxLength(50);
    		this.Property(t => t.Rerackid).HasColumnName("Rerackid").HasMaxLength(20);
    		this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(255);
    		this.Property(t => t.Status).HasColumnName("Status").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").IsRequired().HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.HasOptional(t => t.Rack1).WithMany(t => t.Racks1).HasForeignKey(d => d.Rerackid);
    	}
    }
}
