//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class StockDetail_Mapping : EntityTypeConfiguration<StockDetail>
    {
        public StockDetail_Mapping()
        {					
    		this.HasKey(t => new {t.Did, t.Buttressno, t.Detailseqno});		
    		this.ToTable("StockDetails");
    		this.Property(t => t.Did).HasColumnName("Did").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Buttressno).HasColumnName("Buttressno").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Detailseqno).HasColumnName("Detailseqno").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
    		this.Property(t => t.Memoryid).HasColumnName("Memoryid");
    		this.Property(t => t.Memorycard).HasColumnName("Memorycard").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Floors).HasColumnName("Floors").HasMaxLength(20);
    		this.Property(t => t.Unit).HasColumnName("Unit");
    		this.Property(t => t.Hottoys).HasColumnName("Hottoys");
    		this.Property(t => t.Curinrpieces).HasColumnName("Curinrpieces");
    		this.Property(t => t.CurinWeight).HasColumnName("CurinWeight");
    		this.Property(t => t.Curoutrpieces).HasColumnName("Curoutrpieces");
    		this.Property(t => t.CuroutWeight).HasColumnName("CuroutWeight");
    		this.Property(t => t.Rpieces).HasColumnName("Rpieces");
    		this.Property(t => t.Weight).HasColumnName("Weight");
    		this.Property(t => t.Status).HasColumnName("Status").HasMaxLength(20);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.Property(t => t.Ispacklist).HasColumnName("Ispacklist");
    		this.Property(t => t.Isbuttressall).HasColumnName("Isbuttressall");
    	}
    }
}
