//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.EFRepository.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Logistics.Domain.Entities;
    
    internal partial class Store_Mapping : EntityTypeConfiguration<Store>
    {
        public Store_Mapping()
        {					
    		this.HasKey(t => t.Storeid);		
    		this.ToTable("Stores");
    		this.Property(t => t.Storeid).HasColumnName("Storeid");
    		this.Property(t => t.Names).HasColumnName("Names").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Shortname).HasColumnName("Shortname").HasMaxLength(50);
    		this.Property(t => t.Mncode).HasColumnName("Mncode").HasMaxLength(20);
    		this.Property(t => t.Principals).HasColumnName("Principals").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Phones).HasColumnName("Phones").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Mobiles).HasColumnName("Mobiles").HasMaxLength(20);
    		this.Property(t => t.Totalarea).HasColumnName("Totalarea");
    		this.Property(t => t.Indoorarea).HasColumnName("Indoorarea");
    		this.Property(t => t.Outdoorarea).HasColumnName("Outdoorarea");
    		this.Property(t => t.Restoreid).HasColumnName("Restoreid");
    		this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(500);
    		this.Property(t => t.Remark).HasColumnName("Remark").HasMaxLength(255);
    		this.Property(t => t.Status).HasColumnName("Status").IsRequired().HasMaxLength(20);
    		this.Property(t => t.Modifyuser).HasColumnName("Modifyuser").IsRequired().HasMaxLength(12);
    		this.Property(t => t.Modifytime).HasColumnName("Modifytime");
    		this.HasOptional(t => t.Store1).WithMany(t => t.Stores1).HasForeignKey(d => d.Restoreid);
    	}
    }
}
