//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public long Bid { get; set; }
        public int Recordid { get; set; }
        public long Memoryid { get; set; }
        public string Memorycard { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> Itemtime { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> Inweight { get; set; }
        public Nullable<decimal> Outweight { get; set; }
        public Nullable<decimal> Sweight { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<decimal> Computation { get; set; }
        public Nullable<decimal> Storefee { get; set; }
        public string Status { get; set; }
        public string Createuser { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
    
        public virtual BillRecord BillRecord { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Memorycard Memorycard1 { get; set; }
    }
}
