//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int RecordId { get; set; }
        public long Memoryid { get; set; }
        public string Memorycard { get; set; }
        public Nullable<int> Customerid { get; set; }
        public string Customername { get; set; }
        public string Shortname { get; set; }
        public Nullable<bool> Ispay { get; set; }
        public string Scustomerid { get; set; }
        public string Scustomername { get; set; }
        public Nullable<int> ProId { get; set; }
        public string Proname { get; set; }
        public Nullable<decimal> Startweight { get; set; }
        public Nullable<decimal> Endweight { get; set; }
        public Nullable<decimal> Inweight { get; set; }
        public Nullable<decimal> Outweight { get; set; }
        public Nullable<System.DateTime> Stockindate { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Endate { get; set; }
        public int Enddays { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Status { get; set; }
        public string Createuser { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
    
        public virtual BillRecord BillRecord { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
