//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class BillRecord
    {
        public BillRecord()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.Bills = new HashSet<Bill>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fromdate { get; set; }
        public System.DateTime Todate { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string Createuser { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
    
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
