//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Button
    {
        public Button()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public string About { get; set; }
        public string SysController { get; set; }
        public string SysAction { get; set; }
        public int Sort { get; set; }
        public int MenuId { get; set; }
        public string Icon { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public System.DateTime Modifytime { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
