//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRate
    {
        public int Id { get; set; }
        public int Conid { get; set; }
        public string Manualno { get; set; }
        public int Proid { get; set; }
        public Nullable<decimal> Rjdj { get; set; }
        public Nullable<decimal> Rjrgsj { get; set; }
        public Nullable<decimal> Rjtlzxlf { get; set; }
        public Nullable<decimal> Rjsz { get; set; }
        public Nullable<decimal> Rtrkysf { get; set; }
        public Nullable<decimal> Rtrgsj { get; set; }
        public Nullable<decimal> Rttlgyf { get; set; }
        public Nullable<decimal> Rtdbf { get; set; }
        public Nullable<decimal> Rgrkjyf { get; set; }
        public Nullable<decimal> Rgrgsj { get; set; }
        public Nullable<decimal> Rgdbf { get; set; }
        public Nullable<decimal> Rjzxrkysf { get; set; }
        public Nullable<decimal> Rjzxrgsj { get; set; }
        public Nullable<decimal> Rjzxtxf { get; set; }
        public Nullable<decimal> Rjzxdbf { get; set; }
        public Nullable<decimal> Rjzxdbstart { get; set; }
        public Nullable<decimal> Rjzxdbend { get; set; }
        public Nullable<decimal> Cckf { get; set; }
        public Nullable<decimal> Cchc { get; set; }
        public Nullable<decimal> Ccrkmfqstart { get; set; }
        public Nullable<decimal> Ccrkmfqend { get; set; }
        public Nullable<int> Ccrkmfqday { get; set; }
        public Nullable<decimal> Ccykf { get; set; }
        public Nullable<decimal> Ccyhc { get; set; }
        public Nullable<decimal> Ckqc { get; set; }
        public Nullable<decimal> Ckjjr { get; set; }
        public Nullable<decimal> Ghf { get; set; }
        public Nullable<decimal> Fjf { get; set; }
        public Nullable<decimal> Sjts { get; set; }
        public Nullable<decimal> Sjtp { get; set; }
        public Nullable<decimal> Sjsg { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Product Product { get; set; }
    }
}
