//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.Bills = new HashSet<Bill>();
            this.Contracts = new HashSet<Contract>();
            this.Memorycards = new HashSet<Memorycard>();
            this.StockMoves = new HashSet<StockMove>();
            this.Groups = new HashSet<Group>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string MnCode { get; set; }
        public string Phones { get; set; }
        public string Contract { get; set; }
        public string Status { get; set; }
        public string PostCode { get; set; }
        public string Remarks { get; set; }
        public string Manualno { get; set; }
        public string Fexs { get; set; }
        public string Banks { get; set; }
        public string Account { get; set; }
        public string Mobiles { get; set; }
        public string Emails { get; set; }
        public string Idcard { get; set; }
        public bool Trade { get; set; }
        public bool Sign { get; set; }
        public bool Isbatch { get; set; }
        public Nullable<System.DateTime> LastExport { get; set; }
        public bool Ispay { get; set; }
        public string Modifyuser { get; set; }
        public System.DateTime Modifytime { get; set; }
    
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Memorycard> Memorycards { get; set; }
        public virtual ICollection<StockMove> StockMoves { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
