//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Memorycard
    {
        public Memorycard()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public long Memoryid { get; set; }
        public string MemorycardName { get; set; }
        public string Stockinid { get; set; }
        public string Smanualno { get; set; }
        public string Recargoid { get; set; }
        public string Manualno { get; set; }
        public Nullable<int> Customerid { get; set; }
        public string Customername { get; set; }
        public string Conid { get; set; }
        public string Mncode { get; set; }
        public string Arrivalwayid { get; set; }
        public string Arrivalwayname { get; set; }
        public string Carno { get; set; }
        public string Acceptanceid { get; set; }
        public string Acceptance { get; set; }
        public string Sid { get; set; }
        public string Contactor { get; set; }
        public string Proid { get; set; }
        public string Proname { get; set; }
        public string Brandname { get; set; }
        public string Moname { get; set; }
        public string Maname { get; set; }
        public string Baname { get; set; }
        public Nullable<int> Hottoys { get; set; }
        public string Qunit { get; set; }
        public string Wunit { get; set; }
        public Nullable<int> Scurinrpieces { get; set; }
        public Nullable<decimal> ScurinWeight { get; set; }
        public Nullable<int> Scuroutrpieces { get; set; }
        public Nullable<decimal> ScuroutWeight { get; set; }
        public Nullable<int> Srpieces { get; set; }
        public Nullable<decimal> Sweight { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public string Supplyunit { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Isallstockin { get; set; }
        public string Scustomerid { get; set; }
        public string Scustomername { get; set; }
        public Nullable<System.DateTime> Stockindate { get; set; }
        public string Sourceorder { get; set; }
    
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
