//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.ChildMenus = new HashSet<Menu>();
            this.Roles = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string DisplayIcon { get; set; }
        public string MenuNo { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Sort { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public System.DateTime Modifytime { get; set; }
    
        public virtual ICollection<Menu> ChildMenus { get; set; }
        public virtual Menu Menu1 { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
