//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ContractRates = new HashSet<ContractRate>();
            this.ProductBatchs = new HashSet<ProductBatch>();
            this.ProductMaterials = new HashSet<ProductMaterial>();
            this.ProductModules = new HashSet<ProductModule>();
        }
    
        public int Id { get; set; }
        public string Proname { get; set; }
        public Nullable<int> Count { get; set; }
        public string Mncode { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public System.DateTime Modifytime { get; set; }
    
        public virtual ICollection<ContractRate> ContractRates { get; set; }
        public virtual ICollection<ProductBatch> ProductBatchs { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterials { get; set; }
        public virtual ICollection<ProductModule> ProductModules { get; set; }
    }
}
