//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Rack
    {
        public Rack()
        {
            this.Racks1 = new HashSet<Rack>();
        }
    
        public string Rackid { get; set; }
        public string Rackname { get; set; }
        public string Racktype { get; set; }
        public string Rerackid { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public System.DateTime Modifytime { get; set; }
    
        public virtual ICollection<Rack> Racks1 { get; set; }
        public virtual Rack Rack1 { get; set; }
    }
}
