//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Buttons = new HashSet<Button>();
            this.Menus = new HashSet<Menu>();
            this.LoginUsers = new HashSet<LoginUser>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public System.DateTime Modifytime { get; set; }
    
        public virtual ICollection<Button> Buttons { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<LoginUser> LoginUsers { get; set; }
    }
}
