//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        public string Did { get; set; }
        public string Buttressno { get; set; }
        public int Detailseqno { get; set; }
        public long Memoryid { get; set; }
        public string Memorycard { get; set; }
        public string Floors { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Hottoys { get; set; }
        public Nullable<int> Curinrpieces { get; set; }
        public Nullable<decimal> CurinWeight { get; set; }
        public Nullable<int> Curoutrpieces { get; set; }
        public Nullable<decimal> CuroutWeight { get; set; }
        public Nullable<int> Rpieces { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public Nullable<bool> Ispacklist { get; set; }
        public Nullable<int> Isbuttressall { get; set; }
    }
}
