//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Stores1 = new HashSet<Store>();
        }
    
        public int Storeid { get; set; }
        public string Names { get; set; }
        public string Shortname { get; set; }
        public string Mncode { get; set; }
        public string Principals { get; set; }
        public string Phones { get; set; }
        public string Mobiles { get; set; }
        public Nullable<decimal> Totalarea { get; set; }
        public Nullable<decimal> Indoorarea { get; set; }
        public Nullable<decimal> Outdoorarea { get; set; }
        public Nullable<int> Restoreid { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public System.DateTime Modifytime { get; set; }
    
        public virtual ICollection<Store> Stores1 { get; set; }
        public virtual Store Store1 { get; set; }
    }
}
