//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistics.Domain.Entities
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class VenueStaff
    {
        public int Id { get; set; }
        public string Contactor { get; set; }
        public string Idcard { get; set; }
        public Nullable<bool> Sexs { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public int Jobsid { get; set; }
        public int Storeid { get; set; }
        public Nullable<decimal> Storein { get; set; }
        public Nullable<decimal> Storeout { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string Modifyuser { get; set; }
        public System.DateTime Modifytime { get; set; }
    }
}
